// source: sc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var data_pb = require('./data_pb.js');
goog.object.extend(proto, data_pb);
goog.exportSymbol('proto.proto.Response', null, global);
goog.exportSymbol('proto.proto.ResponsePkg', null, global);
goog.exportSymbol('proto.proto.ResultCode', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.ResponsePkg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.ResponsePkg.repeatedFields_, null);
};
goog.inherits(proto.proto.ResponsePkg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.ResponsePkg.displayName = 'proto.proto.ResponsePkg';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.ResponsePkg.repeatedFields_ = [12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.ResponsePkg.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.ResponsePkg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.ResponsePkg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.ResponsePkg.toObject = function(includeInstance, msg) {
  var f, obj = {
    cmdid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    code: jspb.Message.getFieldWithDefault(msg, 2, 0),
    errmsg: jspb.Message.getFieldWithDefault(msg, 10, ""),
    servertime: jspb.Message.getFieldWithDefault(msg, 11, 0),
    articlelistList: jspb.Message.toObjectList(msg.getArticlelistList(),
    data_pb.Article.toObject, includeInstance),
    bloghomeinfo: (f = msg.getBloghomeinfo()) && data_pb.BlogHomeInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.ResponsePkg}
 */
proto.proto.ResponsePkg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.ResponsePkg;
  return proto.proto.ResponsePkg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.ResponsePkg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.ResponsePkg}
 */
proto.proto.ResponsePkg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.proto.Response} */ (reader.readEnum());
      msg.setCmdid(value);
      break;
    case 2:
      var value = /** @type {!proto.proto.ResultCode} */ (reader.readEnum());
      msg.setCode(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrmsg(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setServertime(value);
      break;
    case 12:
      var value = new data_pb.Article;
      reader.readMessage(value,data_pb.Article.deserializeBinaryFromReader);
      msg.addArticlelist(value);
      break;
    case 13:
      var value = new data_pb.BlogHomeInfo;
      reader.readMessage(value,data_pb.BlogHomeInfo.deserializeBinaryFromReader);
      msg.setBloghomeinfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.ResponsePkg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.ResponsePkg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.ResponsePkg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.ResponsePkg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCmdid();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCode();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getErrmsg();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getServertime();
  if (f !== 0) {
    writer.writeInt64(
      11,
      f
    );
  }
  f = message.getArticlelistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      data_pb.Article.serializeBinaryToWriter
    );
  }
  f = message.getBloghomeinfo();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      data_pb.BlogHomeInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional Response cmdId = 1;
 * @return {!proto.proto.Response}
 */
proto.proto.ResponsePkg.prototype.getCmdid = function() {
  return /** @type {!proto.proto.Response} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.proto.Response} value
 * @return {!proto.proto.ResponsePkg} returns this
 */
proto.proto.ResponsePkg.prototype.setCmdid = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional ResultCode code = 2;
 * @return {!proto.proto.ResultCode}
 */
proto.proto.ResponsePkg.prototype.getCode = function() {
  return /** @type {!proto.proto.ResultCode} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.proto.ResultCode} value
 * @return {!proto.proto.ResponsePkg} returns this
 */
proto.proto.ResponsePkg.prototype.setCode = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string errMsg = 10;
 * @return {string}
 */
proto.proto.ResponsePkg.prototype.getErrmsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.ResponsePkg} returns this
 */
proto.proto.ResponsePkg.prototype.setErrmsg = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional int64 serverTime = 11;
 * @return {number}
 */
proto.proto.ResponsePkg.prototype.getServertime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.ResponsePkg} returns this
 */
proto.proto.ResponsePkg.prototype.setServertime = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * repeated Article articleList = 12;
 * @return {!Array<!proto.proto.Article>}
 */
proto.proto.ResponsePkg.prototype.getArticlelistList = function() {
  return /** @type{!Array<!proto.proto.Article>} */ (
    jspb.Message.getRepeatedWrapperField(this, data_pb.Article, 12));
};


/**
 * @param {!Array<!proto.proto.Article>} value
 * @return {!proto.proto.ResponsePkg} returns this
*/
proto.proto.ResponsePkg.prototype.setArticlelistList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.proto.Article=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.Article}
 */
proto.proto.ResponsePkg.prototype.addArticlelist = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.proto.Article, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.ResponsePkg} returns this
 */
proto.proto.ResponsePkg.prototype.clearArticlelistList = function() {
  return this.setArticlelistList([]);
};


/**
 * optional BlogHomeInfo blogHomeInfo = 13;
 * @return {?proto.proto.BlogHomeInfo}
 */
proto.proto.ResponsePkg.prototype.getBloghomeinfo = function() {
  return /** @type{?proto.proto.BlogHomeInfo} */ (
    jspb.Message.getWrapperField(this, data_pb.BlogHomeInfo, 13));
};


/**
 * @param {?proto.proto.BlogHomeInfo|undefined} value
 * @return {!proto.proto.ResponsePkg} returns this
*/
proto.proto.ResponsePkg.prototype.setBloghomeinfo = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ResponsePkg} returns this
 */
proto.proto.ResponsePkg.prototype.clearBloghomeinfo = function() {
  return this.setBloghomeinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ResponsePkg.prototype.hasBloghomeinfo = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * @enum {number}
 */
proto.proto.Response = {
  RESPONSEBEGININDEX: 0
};

/**
 * @enum {number}
 */
proto.proto.ResultCode = {
  SUCCESS: 0,
  FAIL: 1
};

goog.object.extend(exports, proto.proto);
